CREATE TABLE [dbo].[Address]
(
	[ID] UNIQUEIDENTIFIER NOT NULL DEFAULT (NEWSEQUENTIALID()) PRIMARY KEY, 
	[UserID] INT NULL,
	[AddressID] INT NULL, 
	[AddressLine1] NVARCHAR(50) NULL, 
	[AddressLine2] NVARCHAR(50) NULL, 
	[City] NVARCHAR(50) NULL, 
	[StateProvidenceID] INT NULL, 
	[ZipCode] NCHAR(10) NULL, 
	[CreateBy] NVARCHAR(50) NULL, 
	[CreateDate] DATETIME NULL, 
	[LastModifiedBy] NVARCHAR(16) NULL, 
	[LastModifiedDate] DATETIME NULL

	CONSTRAINT [PK_Address] PRIMARY KEY NONCLUSTERED
	([ID] ASC)
	 WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
 ALTER TABLE [dbo].[Address] ADD CONSTRAINT [DF_Address_ID] DEFAULT (NEWID()) for [ID]
 GO	
 ALTER TABLE [dbo].[Address] ADD CONSTRAINT [DF_Address_CreateDate] DEFAULT (GETDATE()) for [CreateDate]
 GO
 ALTER TABLE [dbo].[Address] ADD CONSTRAINT [DF_Address_LastModifiedDate] DEFAULT (GETDATE()) for [LastModifiedDate]
 GO
