CREATE TABLE [dbo].[BillingInfo]
(
	[ID] UNIQUEIDENTIFIER NOT NULL DEFAULT (NEWSEQUENTIALID()) PRIMARY KEY, 
	[UserID] INT NULL, 
	[AddressID] INT NOT NULL, 
	[FirstName] NVARCHAR(50) NOT NULL, 
	[MiddleNme] NVARCHAR(50) NOT NULL, 
	[LastName] NVARCHAR(50) NOT NULL, 
	[Email] NVARCHAR(50) NOT NULL, 
	[PhoneNumber] NVARCHAR(50) NOT NULL, 
	[DisplayName] NVARCHAR(50) NOT NULL, 
	[IsActive] BIT NULL, 
	[CreateBy] NVARCHAR(50) NULL, 
	[CreateDate] DATETIME NULL, 
	[LastModifiedBy] NVARCHAR(16) NULL, 
	[LastModifiedDate] DATETIME NULL 
	CONSTRAINT [PK_BillingInfo] PRIMARY KEY NONCLUSTERED
	([ID] ASC)
	 WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
 ALTER TABLE [dbo].[BillingInfo] ADD CONSTRAINT [DF_BillingInfo_ID] DEFAULT (NEWID()) for [ID]
 GO
 ALTER TABLE [dbo].[BillingInfo] ADD CONSTRAINT [DF_BillingInfo_CreateDate] DEFAULT (GETDATE()) for [CreateDate]
 GO
 ALTER TABLE [dbo].[BillingInfo] ADD CONSTRAINT [DF_BillingInfo_LastModifiedDate] DEFAULT (GETDATE()) for [LastModifiedDate]
 GO