CREATE TABLE [dbo].[CreditCard]
(
	[ID] UNIQUEIDENTIFIER NOT NULL DEFAULT (NEWSEQUENTIALID()) PRIMARY KEY, 
	[CreditCardID] NVARCHAR(50) NOT NULL, 
	[CardNumber] NVARCHAR(50) NOT NULL, 
	[UserID] INT NOT NULL, 
	[ExpirationDate] DATETIME NOT NULL, 
	[CVV] INT NOT NULL
	CONSTRAINT [PK_CreditCard] PRIMARY KEY NONCLUSTERED
	([ID] ASC)
	 WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
ALTER TABLE [dbo].[CreditCard] ADD CONSTRAINT [DF_CreditCard_ID] DEFAULT (NEWID()) for [ID]
 GO
