﻿CREATE TABLE [dbo].[webpages_Roles] (
	[RoleId]                INT            IDENTITY (1, 1) NOT NULL,
	[RoleName]              NVARCHAR (256) NOT NULL,
	CONSTRAINT [PK_webpages_Roles] 
		PRIMARY KEY CLUSTERED ([RoleId] ASC) 
		WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON),
	CONSTRAINT [UQ_webpages_Roles_RoleName] 
		UNIQUE NONCLUSTERED ([RoleName] ASC)
		WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
) ON [PRIMARY];
GO